### ISSUE TITLE
The drop down menu should disappear when hover away our cursor and adding a contact us page in the header should be good!

### ISSUE THREAD

**Issue by PratikforCoding** [ubucon-asia/2024.ubucon.asia#8]
https://github.com/ubucon-asia/2024.ubucon.asia/assets/90355085/471b2455-bbbb-4270-b908-d9b43a499a58

When I hover away my mouse cursor the drop down menu should disappear.

A contact us section in the hover should be a good idea according to me.

**Comment by Saptarshi2002** [comment]
@sukso96100 @PratikforCoding 
> A contact us section in the hover should be a good idea according to me.

I also think adding a "Contact Us" section will be a good idea.

**Comment by sukso96100** [comment]
Well we're using Vanilla framework's navigation component. and that's how it currently works. we have no plans to customize that behavior you suggested. https://vanillaframework.io/docs/patterns/navigation

If you think that behavior is needed. better ways would be submitting issue on Vanilla - or maybe you can also discuss with them on how you can improve it. https://vanillaframework.io/contribute
